/** Complex UI capture contracts and browser instrumentation. */
export type GuidedEventType = 'click'|'input'|'change'|'submit'|'navigation'|'key'|'drag_start'|'drop'|'hover'|'scroll'|'file_upload'|'dialog'|'page_opened'|'download';
export interface LocatorCandidate { kind:'testid'|'role'|'label'|'placeholder'|'name'|'id'|'text'|'css'; value:string; score:number; role?:string; name?:string; }
export interface FrameContext { name:string; urlPattern:string; selector?:string; title?:string; depth:number; }
export interface TableContext { headers:string[]; rowValues:string[]; rowKey:string; columnIndex:number; columnHeader:string; visibleRowCount:number; declaredRowCount?:number; virtualized:boolean; }
export interface ComponentContext { type:string; name?:string; framework?:string; table?:TableContext; shadowHosts?:Array<{tag:string;id?:string;testId?:string;name?:string}>; }
export interface GuidedEvent { type:GuidedEventType; at:string; pageId:string; urlPattern:string; frames:FrameContext[]; target:Record<string,unknown>; component:ComponentContext; detail:Record<string,unknown>; correlatedNetwork?:Array<Record<string,unknown>>; }

/**
 * Reusable framework function `guidedCaptureScript`.
 * Business Use: Captures semantic complex-UI interactions without recording typed secrets.
 * Benefit: Gives deterministic generation evidence for grids, frames, shadow DOM and advanced gestures.
 */
export function guidedCaptureScript(): string { return String.raw`(() => {
  if (window.__testigentCaptureInstalled) return; window.__testigentCaptureInstalled = true;
  const emit = (type,target,detail={}) => { try {
    const path = detail.event && typeof detail.event.composedPath === 'function' ? detail.event.composedPath() : [];
    const el = path.find(x => x instanceof Element) || (target instanceof Element ? target : null); if(!el) return;
    const attr=n=>el.getAttribute(n)||''; const text=(el.innerText||el.textContent||'').trim().replace(/\\s+/g,' ').slice(0,180);
    const role=attr('role')||({BUTTON:'button',A:'link',INPUT:'textbox',SELECT:'combobox',TEXTAREA:'textbox'}[el.tagName]||'');
    const labelEl=el.labels&&el.labels.length?el.labels[0]:null;
    const explicitLabel=labelEl?(labelEl.innerText||labelEl.textContent||'').trim():'';
    const accessibleName=attr('aria-label')||explicitLabel||attr('title')||text||attr('name');
    const displayName=accessibleName||attr('placeholder');
    const candidates=[]; const push=(kind,value,score,extra={})=>{if(value&&!candidates.some(x=>x.kind===kind&&x.value===value))candidates.push({kind,value:String(value).slice(0,220),score,...extra});};
    push('testid',attr('data-testid')||attr('data-test')||attr('data-qa'),.99); if(role&&accessibleName)push('role',accessibleName,.95,{role,name:String(accessibleName).slice(0,160)});
    if(labelEl)push('label',(labelEl.innerText||labelEl.textContent||'').trim(),.93); push('placeholder',attr('placeholder'),.88); push('name',attr('name'),.82); push('id',attr('id'),.75); if(text&&text.length<=100)push('text',text,.70);
    const css=[]; let node=el,depth=0; while(node&&node.nodeType===1&&depth<4){let part=node.tagName.toLowerCase(); const tid=node.getAttribute('data-testid')||node.getAttribute('data-test')||node.getAttribute('data-qa'); const id=node.getAttribute('id'); if(tid){part+='[data-testid="'+CSS.escape(tid)+'"]';css.unshift(part);break;} if(id&&!/\\d{5,}|[0-9a-f]{8,}/i.test(id)){part+='#'+CSS.escape(id);css.unshift(part);break;} const name=node.getAttribute('name'); if(name)part+='[name="'+CSS.escape(name)+'"]';css.unshift(part);node=node.parentElement;depth++;} push('css',css.join(' > '),.35);
    const shadowHosts=[]; let rt=el.getRootNode(); while(rt&&rt instanceof ShadowRoot){const h=rt.host;shadowHosts.unshift({tag:h.tagName.toLowerCase(),id:h.id||'',testId:h.getAttribute('data-testid')||'',name:h.getAttribute('aria-label')||h.getAttribute('name')||''});rt=h.getRootNode();}
    const closest=s=>{try{return el.closest(s)}catch{return null}};
    const grid=closest('table,[role="table"],[role="grid"],[role="treegrid"],.ag-root,.ag-root-wrapper,.MuiDataGrid-root,.p-datatable,.k-grid,.dx-datagrid'); let component={type:'element',name:'',shadowHosts};
    if(grid){let framework='generic';const c=String(grid.className||'');if(/ag-root/.test(c))framework='ag-grid';else if(/MuiDataGrid/.test(c))framework='mui-datagrid';else if(/p-datatable/.test(c))framework='primeng';else if(/k-grid/.test(c))framework='kendo';else if(/dx-datagrid/.test(c))framework='devextreme'; const rows=[...grid.querySelectorAll('tr,[role="row"]')];const headers=[...grid.querySelectorAll('th,[role="columnheader"]')].slice(0,40).map(x=>(x.innerText||x.textContent||'').trim().replace(/\\s+/g,' ').slice(0,100));const row=closest('tr,[role="row"]');const cells=row?[...row.querySelectorAll('th,td,[role="gridcell"],[role="cell"]')]:[];const cell=closest('th,td,[role="gridcell"],[role="cell"]');const ci=cell?Math.max(0,cells.indexOf(cell)):-1;const values=cells.slice(0,20).map(x=>(x.innerText||x.textContent||'').trim().replace(/\\s+/g,' ').slice(0,120));const rowKey=(row&&(row.getAttribute('data-row-key')||row.getAttribute('data-id')||row.getAttribute('data-key')))||values.find(v=>v&&v.length<=80)||'';const declared=Number(grid.getAttribute('aria-rowcount')||0);component={type:grid.getAttribute('role')||'table',name:grid.getAttribute('aria-label')||grid.getAttribute('data-testid')||'',framework,shadowHosts,table:{headers,rowValues:values,rowKey,columnIndex:ci,columnHeader:ci>=0?(headers[ci]||''):'',visibleRowCount:rows.length,declaredRowCount:declared||undefined,virtualized:Boolean(declared&&declared>rows.length)||/virtual|viewport|ag-center-cols/.test(c)}};}
    else {const dialog=closest('[role="dialog"],dialog'),tabs=closest('[role="tablist"]'),menu=closest('[role="menu"],.menu,.dropdown-menu'),accordion=closest('[aria-expanded],details'),canvas=closest('canvas');if(dialog)component={type:'dialog',name:dialog.getAttribute('aria-label')||dialog.getAttribute('aria-labelledby')||'',shadowHosts};else if(tabs)component={type:'tabs',name:tabs.getAttribute('aria-label')||'',shadowHosts};else if(menu)component={type:'menu',name:menu.getAttribute('aria-label')||'',shadowHosts};else if(canvas)component={type:'canvas',name:canvas.getAttribute('aria-label')||canvas.id||'',shadowHosts};else if(accordion)component={type:'accordion',name:accordion.getAttribute('aria-label')||'',shadowHosts};}
    const rect=el.getBoundingClientRect(); const targetInfo={tag:el.tagName.toLowerCase(),role,name:String(displayName||'').slice(0,160),text,inputType:attr('type'),testId:attr('data-testid')||attr('data-test')||attr('data-qa'),locatorCandidates:candidates}; const extra={...detail};delete extra.event;
    if(el.tagName==='CANVAS'&&detail.clientX!=null)extra.canvas={x:Math.round(detail.clientX-rect.left),y:Math.round(detail.clientY-rect.top),width:Math.round(rect.width),height:Math.round(rect.height)};
    if(el instanceof HTMLInputElement&&el.type==='file')extra.fileUpload={count:el.files?el.files.length:0,extensions:el.files?[...el.files].map(f=>{const i=f.name.lastIndexOf('.');return i>=0?f.name.slice(i).toLowerCase():'';}):[]};
    window.__knowledgeEvent?.({type,at:new Date().toISOString(),urlPattern:location.origin+location.pathname,target:targetInfo,component,detail:extra}).catch(()=>{});
  } catch {} };
  const textEntry=el=>el instanceof HTMLTextAreaElement||(el instanceof HTMLInputElement&&!['button','checkbox','color','file','hidden','image','radio','range','reset','submit'].includes((el.type||'text').toLowerCase()));
  const inputTimers=new WeakMap();
  document.addEventListener('click',e=>emit('click',e.target,{event:e,clientX:e.clientX,clientY:e.clientY}),true);
  document.addEventListener('input',e=>{const el=e.target;if(!textEntry(el))return;const previous=inputTimers.get(el);if(previous)clearTimeout(previous);inputTimers.set(el,setTimeout(()=>{inputTimers.delete(el);emit('input',el,{valuePresent:true});},180));},true);
  document.addEventListener('change',e=>{const el=e.target;if(el instanceof HTMLInputElement&&el.type==='file'){emit('file_upload',el,{event:e});return;}if(textEntry(el))return;const detail={event:e};if(el instanceof HTMLInputElement&&(el.type==='checkbox'||el.type==='radio'))detail.checked=el.checked;emit('change',el,detail);},true);
  document.addEventListener('submit',e=>emit('submit',e.target,{event:e}),true);
  document.addEventListener('keydown',e=>{const a=['Enter','Escape','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'];if(textEntry(e.target)&&e.key==='Enter'){const pending=inputTimers.get(e.target);if(pending){clearTimeout(pending);inputTimers.delete(e.target);}emit('input',e.target,{event:e,valuePresent:true,committedBy:'Enter'});}if(a.includes(e.key)||e.ctrlKey||e.metaKey||e.altKey)emit('key',e.target,{event:e,key:e.key,ctrl:e.ctrlKey,meta:e.metaKey,alt:e.altKey,shift:e.shiftKey});},true);
  let nativeDrag=0;document.addEventListener('dragstart',e=>{nativeDrag=Date.now();emit('drag_start',e.target,{event:e});},true);document.addEventListener('drop',e=>emit('drop',e.target,{event:e}),true);
  let pd=null;document.addEventListener('pointerdown',e=>{if(e.button===0)pd={target:e.target,x:e.clientX,y:e.clientY};},true);document.addEventListener('pointerup',e=>{if(!pd)return;const d=Math.hypot(e.clientX-pd.x,e.clientY-pd.y);if(d>24&&Date.now()-nativeDrag>750){emit('drag_start',pd.target,{event:e,pointerInferred:true});emit('drop',e.target,{event:e,pointerInferred:true});}pd=null;},true);
  let hover='',hoverAt=0;document.addEventListener('pointerover',e=>{const el=e.target instanceof Element?e.target:null;if(!el||el===document.documentElement||el===document.body)return;const k=(el.getAttribute('data-testid')||el.getAttribute('aria-label')||el.textContent||el.tagName).trim().slice(0,80);if(k&&k!==hover&&Date.now()-hoverAt>400){hover=k;hoverAt=Date.now();emit('hover',el,{event:e});}},true);
  let scrollTimer=0;addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>emit('scroll',document.documentElement,{scrollY:Math.round(scrollY),scrollHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight,nearBottom:scrollY+innerHeight>=document.documentElement.scrollHeight-120}),150);},true);
})();`; }
