import type { AdoptionSummary } from '../adoption/adoption.types.js';

/** Standalone pilot/adoption evidence page. Sparse samples are shown as insufficient evidence instead of marketing claims. */
export function renderAdoptionIntelligenceHtml(summary: AdoptionSummary): string {
  const rows = summary.metrics.map(metric => `<tr><td>${escapeHtml(metric.metric)}</td><td>${metric.samples}</td><td>${metric.median} ${escapeHtml(metric.unit)}</td><td>${metric.p90} ${escapeHtml(metric.unit)}</td><td>${metric.baselineMedian === null ? '—' : `${metric.baselineMedian} ${escapeHtml(metric.unit)}`}</td><td>${metric.medianDeltaPercent === null ? '—' : `${metric.medianDeltaPercent}%`}</td><td><span class="state ${stateClass(metric.claimStatus)}">${escapeHtml(metric.claimStatus)}</span></td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TestigentAI Adoption Intelligence</title><style>${styles()}</style></head><body><main><a href="./index.html">← Business dashboard</a><header><div><div class="eyebrow">TESTIGENTAI · ADOPTION INTELLIGENCE</div><h1>Pilot Evidence</h1><p>Measured onboarding, authoring, triage, CI and cost observations. Sparse data is never promoted into a product claim.</p></div><span class="state ${stateClass(summary.pilotStatus)}">${escapeHtml(summary.pilotStatus)}</span></header><section class="cards"><article><span>Observations</span><b>${summary.observations}</b></article><article><span>Applications</span><b>${summary.applications.length}</b></article><article><span>Contributors</span><b>${summary.contributors.length}</b></article><article><span>Measured metrics</span><b>${summary.metrics.length}</b></article></section><section class="panel"><h2>Metric evidence</h2>${rows ? `<div class="table"><table><thead><tr><th>Metric</th><th>Samples</th><th>Median</th><th>P90</th><th>Baseline median</th><th>Delta</th><th>Claim status</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty">No pilot observations recorded yet.</div>'}</section><section class="panel"><h2>Pilot coverage</h2><p>Applications: ${summary.applications.map(escapeHtml).join(', ') || 'none'}<br>Opaque contributor keys: ${summary.contributors.map(escapeHtml).join(', ') || 'none'}</p></section><section class="trust"><b>Truth boundary:</b> ${escapeHtml(summary.truthBoundary)}</section></main></body></html>`;
}
function stateClass(value: string): string { return value === 'PILOT_EVIDENCE_READY' || value === 'IMPROVED' || value === 'MEASURED' ? 'ok' : value === 'REGRESSED' ? 'bad' : 'warn'; }
function escapeHtml(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] ?? char)); }
function styles(): string { return `:root{--bg:#f4f7fb;--panel:#fff;--ink:#0f172a;--muted:#64748b;--line:#dfe7f1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1320px;margin:auto;padding:24px}a{color:#2563eb}header{display:flex;justify-content:space-between;gap:20px;background:#0f172a;color:#fff;padding:24px;border-radius:18px;margin-top:14px}header h1{margin:4px 0 8px}.eyebrow{font-size:10px;letter-spacing:.14em;color:#93c5fd;font-weight:800}header p{color:#cbd5e1;margin:0}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.cards article,.panel,.trust{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.cards span{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:800}.cards b{display:block;font-size:25px;margin-top:5px}.panel{margin-top:14px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;padding:10px;border-bottom:1px solid #eef2f7;font-size:12px}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state{display:inline-block;border-radius:999px;padding:6px 9px;font-size:10px;font-weight:900}.state.ok{background:#d1fae5;color:#065f46}.state.bad{background:#fee2e2;color:#991b1b}.state.warn{background:#fef3c7;color:#92400e}.trust{margin-top:14px;background:#eff6ff;border-left:4px solid #3b82f6;font-size:12px;line-height:1.5}.empty{padding:26px;text-align:center;color:var(--muted)}@media(max-width:850px){.cards{grid-template-columns:repeat(2,1fr)}}`; }
