import type { AgentDecisionRecord } from '../agentic/contracts/agent.types.js';
import type { AgenticIntelligenceSummary } from '../agentic/evidence/agent-decision-ledger.js';

/** Renders a standalone, sanitized one-click agentic decision/provenance report for business and engineering review. */
export function renderAgenticIntelligenceHtml(summary: AgenticIntelligenceSummary, decisions: AgentDecisionRecord[]): string {
  const rows = decisions.map(record => `<tr><td>${escapeHtml(record.timestamp)}</td><td>${escapeHtml(record.agent)}</td><td>${escapeHtml(record.operation)}</td><td><span class="state ${stateClass(record.state)}">${escapeHtml(record.state)}</span></td><td>${record.confidence === null ? '—' : `${Math.round(record.confidence * 100)}%`}</td><td>${record.evidence.length}</td><td>${record.humanApprovalRequired ? (record.humanApproved ? 'Approved' : 'Required') : 'Not required'}</td><td>${escapeHtml(record.rationale)}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TestigentAI Agentic Intelligence</title><style>${styles()}</style></head><body><main><header><div><div class="eyebrow">TESTIGENTAI · AGENTIC INTELLIGENCE</div><h1>Agent Decision Ledger</h1><p>Explainable planner, generator, reviewer, healer and MCP decisions. Agentic evidence cannot rewrite deterministic release facts.</p></div><span class="state ${stateClass(summary.status)}">${escapeHtml(summary.status)}</span></header><section class="cards"><article><span>Decisions</span><b>${summary.decisions}</b></article><article><span>Trusted</span><b>${summary.trusted}</b></article><article><span>Review required</span><b>${summary.reviewRequired}</b></article><article><span>Rejected</span><b>${summary.rejected}</b></article><article><span>Insufficient evidence</span><b>${summary.insufficientEvidence}</b></article><article><span>Degraded</span><b>${summary.degraded}</b></article></section><section class="panel"><h2>Agent activity</h2><div class="agents">${Object.entries(summary.agents).map(([agent, count]) => `<div><span>${escapeHtml(agent)}</span><b>${count}</b></div>`).join('')}</div></section><section class="panel"><h2>Decision evidence</h2>${rows ? `<div class="table"><table><thead><tr><th>Time</th><th>Agent</th><th>Operation</th><th>State</th><th>Confidence</th><th>Evidence</th><th>Human approval</th><th>Rationale</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty">No agentic decisions were recorded for this run.</div>'}</section><section class="trust"><b>Trust boundary:</b> generation/review tools are proposal-only. Source promotion is intentionally outside the v1.7 MCP tool boundary and requires the existing governed review workflow or an explicitly approved future mutation policy.</section></main></body></html>`;
}
function stateClass(value: string): string { return value === 'ACCEPTED' ? 'ok' : value === 'REJECTED' ? 'bad' : value === 'DEGRADED' || value === 'REVIEW_REQUIRED' || value === 'INSUFFICIENT_EVIDENCE' ? 'warn' : 'muted'; }
function escapeHtml(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] ?? char)); }
function styles(): string { return `:root{--bg:#f4f7fb;--panel:#fff;--ink:#0f172a;--muted:#64748b;--line:#dfe7f1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1500px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;gap:20px;background:#0f172a;color:#fff;padding:24px;border-radius:18px}header h1{margin:4px 0 8px}.eyebrow{font-size:10px;letter-spacing:.14em;color:#93c5fd;font-weight:800}header p{color:#cbd5e1;margin:0}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:14px 0}.cards article,.panel,.trust{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.cards span{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:800}.cards b{display:block;font-size:25px;margin-top:5px}.panel{margin-top:14px}.panel h2{margin-top:0}.agents{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.agents div{display:flex;justify-content:space-between;border:1px solid var(--line);padding:10px;border-radius:10px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1100px}th,td{text-align:left;padding:10px;border-bottom:1px solid #eef2f7;font-size:12px;vertical-align:top}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state{display:inline-block;border-radius:999px;padding:6px 9px;font-size:10px;font-weight:900}.state.ok{background:#d1fae5;color:#065f46}.state.bad{background:#fee2e2;color:#991b1b}.state.warn{background:#fef3c7;color:#92400e}.state.muted{background:#e2e8f0;color:#475569}.trust{margin-top:14px;background:#eff6ff;border-left:4px solid #3b82f6;font-size:12px;line-height:1.5}.empty{padding:28px;text-align:center;color:var(--muted)}@media(max-width:950px){.cards{grid-template-columns:repeat(3,1fr)}.agents{grid-template-columns:repeat(2,1fr)}}` ; }
