import type { AiProviderHealthSummary } from '../ai/ai-provider-health.store';

/** Renders the one-click operational drill-down for live AI-provider health. */
export function renderAiProviderHealthHtml(summary: AiProviderHealthSummary): string {
  const rows = summary.recent.map(item => `<tr><td>${escapeHtml(item.recordedAt)}</td><td><b>${item.status}</b></td><td>${escapeHtml(item.providers.join(' → ') || '—')}</td><td>${escapeHtml(item.model ?? '—')}</td><td>${item.providerCheckOutcome}</td><td>${item.healingOutcome}</td><td>${item.generationLatencyMs ?? '—'}</td><td>${escapeHtml(item.errorKind ?? '—')}</td></tr>`).join('');
  const latest = summary.latest;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TestigentAI AI Provider Health</title><style>body{font-family:Inter,Arial,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:32px}.shell{max-width:1180px;margin:auto}.card{background:#111c33;border:1px solid #334155;border-radius:16px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.metric{background:#16213a;padding:14px;border-radius:12px}.metric b{display:block;font-size:24px;margin-top:6px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px;border-bottom:1px solid #334155;text-align:left}a{color:#93c5fd}.note{color:#94a3b8;line-height:1.5}.healthy{color:#86efac}.degraded,.misconfigured{color:#fca5a5}.skipped{color:#cbd5e1}</style></head><body><main class="shell"><a href="./index.html">← Business dashboard</a><h1>Live AI Provider Health</h1><p class="note">Operational canary only. Provider availability is deliberately separate from deterministic AI safety/release correctness.</p><section class="card"><div class="grid"><div class="metric">Current status<b class="${summary.status.toLowerCase()}">${summary.status}</b></div><div class="metric">Recent availability<b>${summary.availabilityPercent === null ? 'N/A' : `${summary.availabilityPercent}%`}</b></div><div class="metric">Canary samples<b>${summary.samples}</b></div><div class="metric">Avg generation latency<b>${summary.averageGenerationLatencyMs === null ? 'N/A' : `${summary.averageGenerationLatencyMs} ms`}</b></div></div>${latest ? `<p class="note">Latest: ${escapeHtml(latest.providers.join(' → ') || 'unconfigured')} / ${escapeHtml(latest.model ?? 'n/a')} · run ${escapeHtml(latest.runId)}</p>` : '<p class="note">No live-provider canary history has been recorded yet.</p>'}</section><section class="card"><h2>Recent canaries</h2>${rows ? `<table><thead><tr><th>Recorded</th><th>Status</th><th>Provider</th><th>Model</th><th>Provider check</th><th>Healing check</th><th>Generation ms</th><th>Error class</th></tr></thead><tbody>${rows}</tbody></table>` : '<p class="note">No canary evidence available.</p>'}</section><section class="card"><h2>Truth boundary</h2><p class="note">A DEGRADED canary means the configured external provider or live AI journey was unavailable at that time. It does not rewrite deterministic test outcomes, false-heal safety, retry/failover contracts, evidence provenance, or the release decision.</p></section></main></body></html>`;
}
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] ?? c)); }
