import type { BreakingChange, ResponseContractResult } from '../api-contract/openapi.types.js';

export interface ApiContractIntelligenceSummary {
  status: 'NO_EVIDENCE' | 'PASS' | 'BREAKING_CHANGES' | 'VALIDATION_FAILURES';
  specification?: string;
  operations?: number;
  breakingChanges?: BreakingChange[];
  responseValidations?: ResponseContractResult[];
  generatedAt?: string;
}

/** One-click API contract evidence page. */
export function renderApiContractIntelligenceHtml(summary: ApiContractIntelligenceSummary): string {
  const changes = (summary.breakingChanges ?? []).map(item => `<tr><td>${escapeHtml(item.kind)}</td><td>${escapeHtml(item.location)}</td><td>${escapeHtml(item.message)}</td></tr>`).join('');
  const validations = (summary.responseValidations ?? []).map(item => `<tr><td>${escapeHtml(item.method)} ${escapeHtml(item.path)}</td><td>${item.status}</td><td>${escapeHtml(item.contentType)}</td><td><span class="state ${item.ok ? 'ok' : 'bad'}">${item.ok ? 'PASS' : 'FAIL'}</span></td><td>${item.violations.map(value => `${escapeHtml(value.path)}: ${escapeHtml(value.message)}`).join('<br>') || '—'}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TestigentAI API Contract Intelligence</title><style>${styles()}</style></head><body><main><a href="./index.html">← Business dashboard</a><header><div><div class="eyebrow">TESTIGENTAI · API CONTRACT INTELLIGENCE</div><h1>OpenAPI Contract Evidence</h1><p>Deterministic schema validation and conservative breaking-change detection for service-heavy teams.</p></div><span class="state ${summary.status === 'PASS' ? 'ok' : summary.status === 'NO_EVIDENCE' ? 'warn' : 'bad'}">${escapeHtml(summary.status)}</span></header><section class="cards"><article><span>Operations</span><b>${summary.operations ?? 0}</b></article><article><span>Breaking changes</span><b>${summary.breakingChanges?.length ?? 0}</b></article><article><span>Validations</span><b>${summary.responseValidations?.length ?? 0}</b></article></section><section class="panel"><h2>Breaking changes</h2>${changes ? `<div class="table"><table><thead><tr><th>Kind</th><th>Location</th><th>Message</th></tr></thead><tbody>${changes}</tbody></table></div>` : '<div class="empty">No breaking-change evidence recorded for this run.</div>'}</section><section class="panel"><h2>Response validations</h2>${validations ? `<div class="table"><table><thead><tr><th>Operation</th><th>Status</th><th>Content type</th><th>Result</th><th>Violations</th></tr></thead><tbody>${validations}</tbody></table></div>` : '<div class="empty">No response-contract validations recorded for this run.</div>'}</section><section class="trust"><b>Truth boundary:</b> The built-in validator intentionally supports a documented OpenAPI 3 schema subset. Unsupported external references or ambiguous schemas fail closed instead of being silently treated as valid.</section></main></body></html>`;
}
function escapeHtml(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] ?? char)); }
function styles(): string { return `:root{--bg:#f4f7fb;--panel:#fff;--ink:#0f172a;--muted:#64748b;--line:#dfe7f1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1320px;margin:auto;padding:24px}a{color:#2563eb}header{display:flex;justify-content:space-between;gap:20px;background:#0f172a;color:#fff;padding:24px;border-radius:18px;margin-top:14px}header h1{margin:4px 0 8px}.eyebrow{font-size:10px;letter-spacing:.14em;color:#a7f3d0;font-weight:800}header p{color:#cbd5e1;margin:0}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.cards article,.panel,.trust{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.cards span{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:800}.cards b{display:block;font-size:25px;margin-top:5px}.panel{margin-top:14px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;padding:10px;border-bottom:1px solid #eef2f7;font-size:12px;vertical-align:top}th{font-size:10px;text-transform:uppercase;color:var(--muted)}.state{display:inline-block;border-radius:999px;padding:6px 9px;font-size:10px;font-weight:900}.state.ok{background:#d1fae5;color:#065f46}.state.bad{background:#fee2e2;color:#991b1b}.state.warn{background:#fef3c7;color:#92400e}.trust{margin-top:14px;background:#eff6ff;border-left:4px solid #3b82f6;font-size:12px;line-height:1.5}.empty{padding:26px;text-align:center;color:var(--muted)}@media(max-width:850px){.cards{grid-template-columns:1fr}}`; }
