import type { FailureIntelligenceSummary } from '../failure-intelligence/failure-intelligence.types.js';

/** Renders deterministic failure classification, clustering and truth-boundary evidence. */
export function renderFailureIntelligenceHtml(summary: FailureIntelligenceSummary, options: { showcase?: boolean; backHref?: string } = {}): string {
  const showcase = options.showcase === true || summary.evidenceMode === 'SHOWCASE';
  const categoryCards = Object.entries(summary.categories).map(([category, count]) => `<article><span>${escapeHtml(category.replaceAll('_', ' '))}</span><b>${count}</b></article>`).join('');
  const clusters = summary.clusters.map(cluster => `<tr><td><code>${escapeHtml(cluster.fingerprint)}</code></td><td>${escapeHtml(cluster.category)}</td><td>${cluster.affectedScenarios}</td><td>${escapeHtml(cluster.applications.join(', '))}</td><td>${escapeHtml(cluster.confidence)}</td><td>${escapeHtml(cluster.recommendation)}</td></tr>`).join('');
  const rows = summary.classifications.map(item => `<tr><td>${escapeHtml(item.scenarioId)}</td><td>${escapeHtml(item.title)}</td><td><span class="pill ${stateClass(item.category)}">${escapeHtml(item.category)}</span></td><td>${escapeHtml(item.confidence)}</td><td><code>${escapeHtml(item.fingerprint)}</code></td><td>${escapeHtml(item.rationale)}</td><td>${escapeHtml(item.recommendation)}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TestigentAI Failure Intelligence</title><style>${styles()}</style></head><body><main><a href="${escapeAttr(options.backHref ?? './index.html')}">← Back</a>${showcase ? '<div class="showcase"><b>SHOWCASE MODE</b><span>Synthetic demonstration evidence · not customer execution data · never claim-eligible</span></div>' : ''}<header><div><div class="eyebrow">TESTIGENTAI · FAILURE INTELLIGENCE</div><h1>Root-cause triage without hiding uncertainty</h1><p>Stable fingerprints compress repeated failures into incidents. Deterministic evidence is evaluated before any optional AI escalation.</p></div><span class="state ${summary.unknownScenarios ? 'warn' : 'ok'}">${summary.unknownScenarios ? `${summary.unknownScenarios} UNKNOWN` : 'EVIDENCE CLASSIFIED'}</span></header><section class="top"><article><span>Failed scenarios analyzed</span><b>${summary.analyzedScenarios}</b></article><article><span>Unique incidents</span><b>${summary.uniqueIncidents}</b></article><article><span>Unknown</span><b>${summary.unknownScenarios}</b></article><article><span>Claim eligible</span><b>${summary.claimEligible ? 'YES' : 'NO'}</b></article></section><section class="categories">${categoryCards}</section><section class="panel"><h2>Incident compression</h2><p class="sub">Multiple scenarios with the same stable evidence fingerprint become one incident for triage.</p>${clusters ? `<div class="table"><table><thead><tr><th>Fingerprint</th><th>Category</th><th>Affected</th><th>Applications</th><th>Confidence</th><th>Recommendation</th></tr></thead><tbody>${clusters}</tbody></table></div>` : '<div class="empty">No failed evidence available.</div>'}</section><section class="panel"><h2>Scenario classifications</h2>${rows ? `<div class="table"><table><thead><tr><th>Scenario</th><th>Title</th><th>Category</th><th>Confidence</th><th>Fingerprint</th><th>Why</th><th>Recommended action</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty">No classifications available.</div>'}</section><section class="trust"><b>Truth boundary:</b> ${escapeHtml(summary.truthBoundary)}</section></main></body></html>`;
}

function stateClass(category: string): string { return category === 'PRODUCT_DEFECT' || category === 'API_CONTRACT_FAILURE' ? 'bad' : category === 'UNKNOWN' ? 'warn' : 'info'; }
function escapeHtml(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] ?? char)); }
function escapeAttr(value: string): string { return escapeHtml(value); }
function styles(): string { return `:root{--bg:#f3f6fb;--panel:#fff;--ink:#0f172a;--muted:#64748b;--line:#dce5ef}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1500px;margin:auto;padding:24px}a{color:#2563eb}.showcase{margin:12px 0;background:#fff7ed;border:1px solid #fdba74;border-left:5px solid #f97316;border-radius:12px;padding:12px 14px;display:flex;gap:12px;align-items:center}.showcase b{color:#9a3412}.showcase span{color:#7c2d12;font-size:12px}header{display:flex;justify-content:space-between;gap:20px;background:#172554;color:white;padding:24px;border-radius:18px;margin-top:12px}header h1{margin:4px 0 8px}.eyebrow{font-size:10px;letter-spacing:.14em;color:#bfdbfe;font-weight:900}header p{margin:0;color:#dbeafe}.top,.categories{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.categories{grid-template-columns:repeat(5,1fr)}.top article,.categories article,.panel,.trust{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.top span,.categories span{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:800}.top b,.categories b{display:block;font-size:25px;margin-top:5px}.categories b{font-size:20px}.panel{margin-top:14px}.sub{color:var(--muted);font-size:12px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1100px}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #edf2f7;font-size:12px}th{font-size:10px;text-transform:uppercase;color:var(--muted)}code{font-size:11px}.pill,.state{display:inline-block;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.pill.bad{background:#fee2e2;color:#991b1b}.pill.warn,.state.warn{background:#fef3c7;color:#92400e}.pill.info{background:#dbeafe;color:#1e3a8a}.state.ok{background:#d1fae5;color:#065f46}.trust{margin-top:14px;border-left:4px solid #3b82f6;background:#eff6ff;font-size:12px;line-height:1.5}.empty{padding:24px;text-align:center;color:var(--muted)}@media(max-width:900px){.top,.categories{grid-template-columns:repeat(2,1fr)}}`; }
